# TODO: redo this here!!
# If you want to run this in prodcution, please create a custom mariadb server!!
services:
  boobles-frontend-dev:
    container_name: boobles_dev_frontend
    image: nginx:alpine
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./boobles_dev_frontend:/usr/share/nginx/html/:ro
      - ./boobles_dev_frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - boobles-backend

  # boobles-frontend:
  #   env_file:
  #     - .env
  #   build: "/boobles_frontend/."
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - boobles-backend
  #   volumes:
  #     - shared-env:/app/shared:ro
  #   entrypoint: >
  #     /bin/sh -c "
  #     echo 'Waiting for API Key...';
  #     while [ ! -f /app/shared/.env ] || ! grep -q 'API_KEY' /app/shared/.env; do
  #       sleep 2;
  #     done;
  #     echo 'API Key found! Copying .env file';
  #     cp /app/shared/.env /.env;
  #     npm run start

  boobles-backend:
    container_name: boobles_backend
    build: "./boobles_backend/."
    restart: always
    depends_on:
      boobles-db:
        condition: service_healthy
    environment:
      first-init: "true"
      tables_path: "sql_statements/tables.sql"
      JWT-Secret: ""
      Database-Conn: "boobles_backend:YOUR-PW-HERE@tcp(boobles-db:3306)/Boobles?parseTime=true"
      env_path: "/app/shared/.env"
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
      - shared-env:/app/shared
      - product-pictures:/app/product-pictures
    links:
      - "boobles-db"

  boobles-db:
    container_name: boobles_db
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "YOUR-SUPER-SECRET-PW-HERE" # CHANGE THIS IF PRODUCTION!!!
      MYSQL_DATABASE: "Boobles" # DO NOT change this!
      MYSQL_USER: "boobles_backend"
      MYSQL_PASSWORD: "YOUR-PW-HERE" # Change this if production! Note that you have to change the connection string
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

# Volume for sharing the .env
volumes:
  shared-env:
  product-pictures:
  logs:
