services:
  # boobles-frontend:
  #   env_file:
  #     - .env
  #   build: "/boobles_frontend/."
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - boobles-backend
  #   volumes:
  #     - shared-env:/app/shared:ro
  #   entrypoint: >
  #     /bin/sh -c "
  #     echo 'Waiting for API Key...';
  #     while [ ! -f /app/shared/.env ] || ! grep -q 'API_KEY' /app/shared/.env; do
  #       sleep 2;
  #     done;
  #     echo 'API Key found! Copying .env file';
  #     cp /app/shared/.env /.env;
  #     npm run start
  #

  boobles-backend:
    build: "/boobles_backend/."
    command: "[/boobles_backend]"
    restart: always
    depends_on:
      boobles-db:
        condition: service_healthy
    environment:
      first-init: "true"
      tables_path: "/boobles_backend/sql_statements/tables.sql"
      JWT-Secret: ""
      Database-Conn: "boobles_backend:YOUR-PW-HERE@tcp(boobles-db:3306)/Boobles?parseTime=true"
    ports:
      - "8080:8080"
    volumes:
      - shared-env:/app/shared
    links:
      - "boobles-db"

  boobles-db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQT_ROOT_PASSWORD: "YOUR-SUPER-SECRET-PW-HERE" # CHANGE THIS IF PRODUCTION!!!
      MYSQL_DATABASE: "Boobles" # DO NOT change this!
      MYSQL_USER: "boobles_backend"
      MYSQL_PASSWORD: "YOUR-PW-HERE" # Change this if production! Note that you have to change the connection string
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

# Volume for sharing the .env
volumes:
  shared-env:
